<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\CourierService.Domain\CourierService.Domain.csproj" />
    <ProjectReference Include="..\CourierService.Offers\CourierService.Offers.csproj" />
    <ProjectReference Include="..\CourierService.Services\CourierService.Services.csproj" />
  </ItemGroup>

</Project>
